export const bossCritiques = [
  "10/10, would meet again",
  "You call that dodging?",
  "I’ve seen snails move faster",
  "Come back when you’re dangerous",
  "My grandma hits harder",
  "That tickled",
  "I died... out of boredom",
  "You got lucky",
  "I wasn’t even trying",
  "That all you got?",
  "Oops, my weakness: bullets",
  "You’re a worthy gnat",
  "I blinked...",
  "Next time, bring skills",
  "Pathetic. Try again.",
  "Just warming up",
  "Too easy. Try hard mode",
  "Not even final boss material",
  "I slipped, okay?",
  "I underestimated you... once",
  "You win this round",
  "What a fluke",
  "Respect. A little.",
  "Fine, take your win",
  "Your aim’s not bad… for once",
  "Lucky crit, huh?",
  "I’ll be back. Stronger.",
  "Don’t tell the others",
  "You’re learning. Scary.",
  "Stop smiling. It’s creepy.",
  "Wasn’t expecting that",
  "I tripped over code",
  "You’ve got potential",
  "You're not the worst I've seen",
  "That was mildly impressive",
  "You outpaced me",
  "GG. No rematch.",
  "You pressed buttons well",
  "Well dodged... once",
  "My health bar was bugged",
  "Okay, you're decent",
  "I let you win",
  "You're not bad... for a human",
  "My AI glitched, obviously",
  "You’re improving. Annoying.",
  "Wow. Just wow.",
  "You surprise me",
  "Consider me... defeated",
  "Well played. I guess.",
  "I saw fear. In your eyes.",
  "Living is easy with eyes closed",
];
